name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Access private repository
        run: |
          git clone https://github.com/YOUR_PRIVATE_REPO/test.git

      - name: Fill disk
        run: |
         fallocate -l 10G huge_file
 
